titulo_Prubeba_doc = "preguntas de Español" 
banco_preguntas = [
    {"tipo": "abierta", "pregunta": "Forma de comunicacion en la que una persona expresa sus ideas ante un publico" , "correcta": "Discurso Oral"},
    {"tipo": "abierta", "pregunta": "Se utila para informar, explicar, descibir algo de forma clara y objetiva", "correcta": "Discurso Expositivo"},
    {"tipo": "abierta", "pregunta": "Relata una historia o evento real o ficticio", "correcta": "Discurso Narrativo"},
    {"tipo": "abierta", "pregunta": "Busca influir o persuadir a la audiencia con un enfoque mas emocional", "correcta": "Discurso Persuasivo"},
    {"tipo": "abierta", "pregunta": "Su objetivo es hacer reir o divertir a la audiencia", "correcta": "Discurso de Entretenimiento"},
    {"tipo": "abierta", "pregunta": "Se utiliza para informar o explicar un tema de manera clara y concisa", "correcta": "Discurso Informativo"},
    {"tipo": "abierta", "pregunta": "Su principal objetivo es inspirar o motivar a la audiencia", "correcta": "Discurso Motivacional"},
    {"tipo": "abierta", "pregunta": "Se utiliza para defender una idea o postura frente a una audiencia", "correcta": "Discurso Argumentativo"},
    {"tipo": "abierta", "pregunta": "Su objetivo es describir algo de forma detallada con fin de visualizarlo", "correcta": "Discurso Descriptivo"},
    {"tipo": "abierta", "pregunta": "Proceso mediante el cual los seres humanos intercambian información, ideas y opiniones", "correcta": "La Comunicacion"},
    {"tipo": "abierta", "pregunta": "Es quien envia el mensaje", "correcta": "El Emisor"},
    {"tipo": "abierta", "pregunta": "Es quien recibe e interpretael mensaje", "correcta": "El Receptor"},
    {"tipo": "abierta", "pregunta": "Es la idea, informacion o emocion que se quiere transmitir", "correcta": "El Mensaje"},
    {"tipo": "abierta", "pregunta": "Es el medio a traves el cual circula el mensaje", "correcta": "El Canal"},
    {"tipo": "abierta", "pregunta": "Son las circunstancias, lugar y situacion que rodean el acto comunicativo", "correcta": "El Contexto"},
    {"tipo": "abierta", "pregunta": "cualquier interferencia que distorsiona la comunicación", "correcta": "el ruido"},
    {"tipo": "abierta", "pregunta": "La respuesta o reacción del receptor al mensaje", "correcta": "La Retroalimentacion"},
    {"tipo": "abierta", "pregunta": "El sistema de signos utilizados para codificar el mensaje", "correcta": "El Codigo"},
    {"tipo": "abierta", "pregunta": "Implica el uso de palabras o lenguaje escrito para transmitir el mensaje", "correcta": "Comunicacion Verbal"},
    {"tipo": "abierta", "pregunta": "Se refiere a la transmision de mensajes sin usar palabras, utilizando gestos, expresiones faciales, posturas y otros elementos no verbales", "correcta": "Comunicacion No Verbal"},
    {"tipo": "abierta", "pregunta": "Es el proceso de comunicacion que tiene lugar dentro de una persona, es decir el dialogo interno que tiene consigo mismo", "correcta": "La Comunicacion Intrapersonal"},
    {"tipo": "abierta", "pregunta": "Es el proceso de comunicacion entre individuos, ya sea en interaccion cara a cara o a trade de medios", "correcta": "La Comunicacion Social"},
    {"tipo": "abierta", "pregunta": "Es la interaccion directa entre dos o mas personas, donde el mensaje se transmite y recie de forma actia entre los participantes", "correcta": "La Comunicacion Interpersonal"},
    {"tipo": "abierta", "pregunta": "Ocurre cuando el mensaje se dirige a un grupo peque;o de personas", "correcta": "La Comunicacion Grupal"},
    {"tipo": "abierta", "pregunta":  "Es el proceso de transmitir un mensaje a una gran cantidad de personas simultaneamente, generalmente a traves de medios como radio y television", "correcta": "La Comunicacion Masiva"},
    {"tipo": "abierta", "pregunta": "Se da en contextos estructurados como instituciones, empresas donde siguen normas y protocolos especificos", "correcta": "La Comunicacion Formal"},
    {"tipo": "abierta", "pregunta": "Es mas espontanea y relajada, generalmente no sigue ni un formato o estrucciones rigidas", "correcta": "La Comunicacion Informal"},
    {"tipo": "abierta", "pregunta": "El mensaje fluye en una sola direccion, del emisor a varios receptores sin esperar retroalimentacion inmediata", "correcta": "Comunicacion Unilateral"},
    {"tipo": "abierta", "pregunta": "Los participantes interactuan entre si, el mensaje fluye en multiples direccinones con una interaccion activa entre los participantes", "correcta": "Comunicacion Multilateral"},
    {"tipo": "abierta", "pregunta": "Es la capacidad de expresar ideas y emociones mediante el habla" , "correcta": "Expresion Oral"},
    {"tipo": "abierta", "pregunta": "Es el conjunto de se;ales gestos, expresiones, posturas, miradas y otros elementos que no emplrean palabras", "correcta": "Lenguage No Verbal"},
    {"tipo": "abierta", "pregunta": "Son aquellos aspectos de la comunicacion que no utilizan palabras pero son cruciales para transmitir un ensaje complejo y efectivo" , "correcta": "Elementos No Verbales"},
    {"tipo": "abierta", "pregunta": "Son los distintos tipos de palabras que existen en una lengua, y que se agrupan segun su funcion gramatical", "correcta": "Categorias Gramaticales"},
    {"tipo": "abierta", "pregunta": "Son las palabras que se utilizan para nombrar personas, lugares, cosas o ideas", "correcta": "Sustantivos"},
    {"tipo": "abierta", "pregunta": "Son las palabras que se utilizan para describir o calificar a los sustantivos", "correcta": "Adjetivos"},
    {"tipo": "abierta", "pregunta": "Son las palabras que se utilizan para expresar acciones, estados o procesos", "correcta": "Verbos"},
    {"tipo": "abierta", "pregunta": "Son las palabras que se utilizan para expresar relaciones entre palabras o frases", "correcta": "Preposiciones"},
    {"tipo": "abierta", "pregunta": "Son las palabras que se utilizan para conectar oraciones o partes de una oración", "correcta": "Conjunciones"},
    {"tipo": "abierta", "pregunta": "Son las palabras que se utilizan para expresar emociones, sentimientos o ideas", "correcta": "Interjecciones"},
    {"tipo": "abierta", "pregunta": "Son las palabras que se utilizan para sustituir a los sustantivos y evitar su repeticion", "correcta": "Pronombres"},
    {"tipo": "abierta", "pregunta": "Modifican a los verbos, adjetivos u otros adverbios, indicando modo, tiempo, lugar, cantidad o intensidad", "correcta": "Adverbios"},
    {"tipo": "abierta", "pregunta": "Enlazan palabras, frases u oraciones", "correcta": "Conjunciones"},

    # Ejemplo de Selección Múltiple
    {"tipo": "multiple", "pregunta": "¿Qué discurso usa recursos literarios para crear una imagen mental?", "correcta": "Discurso Descriptivo", "opciones": ["Descriptivo", "Expositivo", "Argumentativo"]},
    
    # Ejemplo de Enumeración
    {"tipo": "enumeracion", "pregunta": "Nombra los elementos de la comunicación (8)", "correcta": ["Emisor", "Receptor", "Mensaje", "Canal", "Ruido", "Retroalimentación", "Código", "Contexto"]}, 
    {"tipo": "enumeracion", "pregunta": "Nombra los tipos de comunicación (8)", "correcta": ["Intrapersonal", "Interpersonal", "Grupal", "Masiva", "Formal", "Informal", "Unilateral", "Multilateral"]},
    {"tipo": "enumeracion", "pregunta": "Nombra las situaciones comunicativas (6)", "correcta": ["Formales", "Informales", "Educativas", "Laborales", "Emergencias", "Entretenimiento"]},
    {"tipo": "enumeracion", "pregunta": "Nombra las categorias gramaticales (8)", "correcta": ["Sustantivos", "Adjetivos", "Verbos", "Adverbios", "Preposiciones", "Conjunciones", "Interjecciones", "Pronombres"]}, 
    {"tipo": "enumeracion", "pregunta": "Nombra los tipos de discursos (8)", "correcta": ["Expositivo", "Narrativo", "Persuasivo", "Entretenimiento", "Informativo", "Motivacional", "Argumentativo", "Descriptivo"]},
    {"tipo": "enumeracion", "pregunta": "Nombra los elementos no verbales (6)", "correcta": ["Gestos", "Proxemica", "Postura Corporal", "Tono De Voz", "Contacto Visual", "Paralingüística"]},
    {"tipo": "enumeracion", "pregunta": "Nombra las características del lenguaje no verbal (9)", "correcta": ["Universal", "Ambiguo", "Subconciente", "Contextual", "Expresa Emociones", "Cultural", "Intensificación o Contradicción del Lenguaje Verbal", "Canales Múltiples", "Interacción social"]},
    {"tipo": "enumeracion", "pregunta": "Nombra que indica la proxémica (2)", "correcta": ["Inicio/Cierre", "Cercanía"]},
    {"tipo": "enumeracion", "pregunta": "Nombra que indica la paralingüística (3)", "correcta": ["Tono de Voz", "Volumen", "Ritmo"]}
    ]

